spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/clover
    username: clover
    password: clover
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        generate_statistics: false
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: false
    generate-ddl: true


logging:
  level:
    org:
      springframework:
        security: info
        web: info
      hibernate:
        type: info
    root: info

# Authentication properties used by JWT generation
jwt:
  pass-phrase: HvA is the best school ever. Nothing comes even close.
  issuer: HvA

email:
  sender: ${INFO_DEV_EMAIL}
  username: ${INFO_DEV_EMAIL}
  password: ${INFO_DEV_PASSWORD}

payment.secrets:
  api-key: ${STRIPE_DEV_API_KEY}
  webhook-secret: ${STRIPE_DEV_WEBHOOK_SECRET}